language: python
python:
  - "3.8"


before_install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade libssl1.1

install:
  - pip install -r requirements.txt

script:
  - streamlit run app.py --server.headless true
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
