language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - streamlit run app.py --server.headless true
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
